---
- name: Gather instance Facts
  action: ec2_facts

- name: check wget version
  shell: wget -V | grep -i 'GNU Wget'
  register: wget_version

- name: check NTP version
  shell: ntpq -crv | grep -i 'version' | awk '{print $2}'
  register: NTP_version

- debug: var=ansible_ec2_instance_id

- debug: var=ansible_ec2_local_ipv4

- name: create report
  action: template src=report.j2 dest=/root/{{ ansible_ec2_local_ipv4 }}

- name: move file in reports directory
  fetch: src=/root/{{ ansible_ec2_local_ipv4 }} dest={{ report_directory_path }}/{{ ansible_ec2_local_ipv4 }} flat=yes

- name: delete report from remote host
  file: path=/root/{{ ansible_ec2_local_ipv4 }} state=absent
